using OstranautsTranslator.Core;

namespace OstranautsTranslator.Tool;

internal sealed class ExportNativeModCommandOptions
{
   public required string GameRootPath { get; init; }

   public required string WorkspacePath { get; init; }

   public required string ToLanguage { get; init; }

   public required string ModId { get; init; }

   public required string ModName { get; init; }

   public string Author => RuntimeTranslationDeployment.DefaultAuthor;

   public string ModUrl { get; init; } = string.Empty;

   public string GameVersion { get; init; } = string.Empty;

   public string ModVersion { get; init; } = "1.0.0";

   public string Notes { get; init; } = $"Generated by {RuntimeTranslationDeployment.ToolExecutableName}.";

   public string? OutputPath { get; init; }

   public bool IncludeDraft { get; init; }

   public bool VerifySourceHash { get; init; } = true;

   public static ExportNativeModCommandOptions Parse( IReadOnlyList<string> args )
   {
      var toLanguage = CliTargetLanguageOption.ParseOptionalValue( args );

      var resolvedGameRootPath = RuntimeTranslationDeployment.GetDefaultGameRootPath( AppContext.BaseDirectory );
      var resolvedWorkspacePath = RuntimeTranslationDeployment.GetDefaultWorkspacePath( resolvedGameRootPath );
      var gameVersion = RecordedGameVersionResolver.ResolveRecordedGameVersionOrEmpty( resolvedGameRootPath );

      return new ExportNativeModCommandOptions
      {
         GameRootPath = resolvedGameRootPath,
         WorkspacePath = resolvedWorkspacePath,
         ToLanguage = RuntimeTranslationDeployment.ResolveTargetLanguage( toLanguage ),
         ModId = RuntimeTranslationDeployment.ModId,
         ModName = RuntimeTranslationDeployment.ModName,
         GameVersion = gameVersion,
         OutputPath = null,
         IncludeDraft = true,
         VerifySourceHash = true,
      };
   }
}
