namespace OstranautsTranslator.Tool.Workspace;

internal sealed class CorpusWorkspace
{
   public CorpusWorkspace( string rootPath )
   {
      RootPath = Path.GetFullPath( rootPath );
      CorpusDatabasePath = Path.Combine( RootPath, "corpus.sqlite" );
      ReferenceDirectoryPath = Path.Combine( RootPath, "reference" );
      RuntimeMissImportsDirectoryPath = Path.Combine( RootPath, "imports", "runtime-miss" );
      SourceExportsDirectoryPath = Path.Combine( RootPath, "exports", "source" );
      RuntimeExportsDirectoryPath = Path.Combine( RootPath, "exports", "runtime" );
   }

   public string RootPath { get; }

   public string CorpusDatabasePath { get; }

   public string ReferenceDirectoryPath { get; }

   public string RuntimeMissImportsDirectoryPath { get; }

   public string SourceExportsDirectoryPath { get; }

   public string RuntimeExportsDirectoryPath { get; }

   public string TranslationImportsDirectoryPath => Path.Combine( RootPath, "imports", "translations" );

   public string GetGlossaryPath( string fromLanguage, string toLanguage )
   {
      return Path.Combine( ReferenceDirectoryPath, $"glossary-{fromLanguage}-to-{toLanguage}.json" );
   }

   public string GetTranslationDatabasePath( string language )
   {
      return CorpusDatabasePath;
   }

   public string GetSourceExportPath( string fromLanguage, string toLanguage )
   {
      return Path.Combine( SourceExportsDirectoryPath, $"source-{fromLanguage}-to-{toLanguage}.jsonl" );
   }

   public string GetTranslationImportPath( string fromLanguage, string toLanguage )
   {
      return Path.Combine( TranslationImportsDirectoryPath, $"translations-{fromLanguage}-to-{toLanguage}.jsonl" );
   }

   public string GetRuntimeExportDirectoryPath( string language )
   {
      return Path.Combine( RuntimeExportsDirectoryPath, language, "Text" );
   }

   public string GetRuntimeExportPath( string language )
   {
      return Path.Combine( GetRuntimeExportDirectoryPath( language ), "_AutoGeneratedTranslations.txt" );
   }

   public string GetRuntimeMissImportDirectoryPath( string language )
   {
      return Path.Combine( RuntimeMissImportsDirectoryPath, language );
   }

   public void EnsureCreated()
   {
      Directory.CreateDirectory( RootPath );
      DeleteObsoleteWorkspaceContent();
      DeleteEmptyWorkspaceScaffolding();
   }

   public void DeleteTransientExports()
   {
      DeleteDirectoryIfExists( SourceExportsDirectoryPath );
      DeleteDirectoryIfExists( RuntimeExportsDirectoryPath );
      DeleteEmptyWorkspaceScaffolding();
   }

   private void DeleteObsoleteWorkspaceContent()
   {
      DeleteDirectoryIfExists( Path.Combine( RootPath, "translations" ) );
      DeleteDirectoryIfExists( Path.Combine( RootPath, "exports", "native-mod" ) );
   }

   private void DeleteEmptyWorkspaceScaffolding()
   {
      DeleteEmptyDirectoryTree( Path.Combine( RootPath, "imports" ) );
      DeleteEmptyDirectoryTree( Path.Combine( RootPath, "exports" ) );
   }

   private static void DeleteDirectoryIfExists( string directoryPath )
   {
      if( Directory.Exists( directoryPath ) )
      {
         Directory.Delete( directoryPath, recursive: true );
      }
   }

   private static void DeleteEmptyDirectoryTree( string directoryPath )
   {
      if( !Directory.Exists( directoryPath ) ) return;

      foreach( var childDirectoryPath in Directory.EnumerateDirectories( directoryPath ) )
      {
         DeleteEmptyDirectoryTree( childDirectoryPath );
      }

      if( !Directory.EnumerateFileSystemEntries( directoryPath ).Any() )
      {
         Directory.Delete( directoryPath );
      }
   }
}
